spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.serializer.EventsAvroSerializer
    topics:
      sensor-topic: telemetry.sensors.v1
      hub-topic: telemetry.hubs.v1
grpc:
  server:
    port: 9090
